# Generated by Django 2.0.4 on 2018-04-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='title',
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
