# Generated by Django 2.0.4 on 2018-04-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180421_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='name',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='photoRef',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='placeId',
            field=models.CharField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='vicinty',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
