# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-21 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180421_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('is_guide', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='place',
            name='id',
        ),
        migrations.AlterField(
            model_name='place',
            name='placeId',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
