# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-18 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('is_guide', models.BooleanField(default=False)),
            ],
        ),
    ]
